---
# tasks file for VeraCrypt

- name: "Compose download URL"
  shell: curl -s -L https://launchpad.net/veracrypt/+download | egrep -i "title.*trunk.*debian\-10\-amd64\.deb.*" | egrep -v "console" | head -n1 | egrep -o "href\=\".*\.deb\"" | awk -F\" '{print $2}'
  register: veracrypt_url
  tags:
    - veracrypt_install

- name: Install VeraCrypt
  apt:
    deb: "{{ veracrypt_url.stdout }}"
